# Generated by Django 5.1.4 on 2025-01-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=5)),
                ('department_name', models.CharField(max_length=50)),
                ('department_hod', models.CharField(max_length=100)),
                ('department_details', models.CharField(max_length=250)),
            ],
        ),
    ]
