# Generated by Django 5.1.4 on 2025-01-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='number_of_employees',
            field=models.IntegerField(null=True),
        ),
    ]
